# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
gems: [jekyll-paginate]
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude

# markdown interpreter and highlighter
highlighter: rouge # pygments

markdown: kramdown # redcarpet 

#redcarpet:
kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

disqus: #dbyll
google_analytics: #dbyll

excerpt_link:   "Read on &rarr;"
excerpt_separator: "<!--more-->"
permalink: none

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "3 Keajaiban Hidup"

description: Stylish Jekyll Theme
author:
  name: "fathon"
  email: "fathon.1994@gmail.com"
  github: "aliffathon"
  twitter: ""
  pinterest: ""
  linkedin: ""
  bio: "Sebuah Perjalanan dimulai dari -Satu Langkah Kecil-"
  description: "Hidup adalah sebuah perjalanan Panjang, hanya -Langkah Kaki- kita yang dapat membawa kita menuju -Akhir-"
  email_md5: c703914cdca7dca8bae568588ee2eb75

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
