title: Tanpa Judul
email: afatonii2016@gmail.com
description: > # ignore newlines until "baseurl:"
  Catatan Penulis
baseurl: ""
url: "http://alif.fathon.my.id"
twitter_username: aliffathon
github_username:  aliffathon

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# exclude from generate
exclude:
- node_modules
- gulpfile.js
- package.json
- package-lock.json

# self service
host: 127.0.0.1
port: 4100

# permalink
permalink: /posts/:title/

# excerpt
excerpt_link: "Read on &rarr;"
excerpt_separator: "<!--more-->"

# categories & tags
categories_path: "categories.html"
tags_path: "tags.html"

permalink: /:title/

author:
  name: aliffathon
  email: alif@fathon.my.id
  url: https://www.fathon.my.id/

plugins:
 - jekyll-paginate

paginate: 5
paginate_path: "page:num"
